FROM ubuntu:latest

RUN apt update && \
    apt install -y sudo curl systemd build-essential perl && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && \
    apt install -y nodejs

COPY password /tmp/password

RUN mkdir /home/mcp && \
    secret=$(perl -e 'print crypt($ARGV[0], "password")' $(cat /tmp/password)) && \
    useradd -m -p "$secret" -s /bin/bash mcp && \
    cp -r /etc/skel/. /home/mcp && \
    usermod -aG sudo mcp && \
    chmod -R 0755 /home/mcp && \
    chown -R mcp:mcp /home/mcp && \
    rm -f /tmp/password

USER mcp
WORKDIR /home/mcp

RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
ENV PATH="/home/mcp/.local/bin:${PATH}"

RUN uv init server
WORKDIR /home/mcp/server
RUN uv add mcp "mcp[cli]"

COPY pyproject.toml /home/mcp/server/pyproject.toml
COPY server.py /home/mcp/server/server.py

USER root
COPY entrypoint.sh /home/mcp/server/entrypoint.sh
RUN chmod +x /home/mcp/server/entrypoint.sh

RUN echo 'source /home/mcp/server/.venv/bin/activate' >> /home/mcp/.bashrc
USER mcp

ENV MCP_HOST='localhost'
ENV MCP_PORT=6274
ENV MCP_API_PORT=6277
ENV MCP_API_URL='http://172.19.0.35:6277'

EXPOSE 6274 6277 3001

ENTRYPOINT [ "/home/mcp/server/entrypoint.sh" ]
# Default command
CMD ["/bin/bash", "-c", "source /home/mcp/server/.venv/bin/activate"]
